baseURL: "https://skndlst.fun/"
title: SKNDLST | Блог
paginate: 3
theme: PaperMod
canonifyURLs: false
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

disqusShortname: skndlst-fun

googleAnalytics: G-VDHW86HXSN

defaultContentLanguage: ru
languageCode: ru-RU

sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: SKNDLST
  description: "Возможно, всё это было не со мной."
  keywords: [skndlst, скндлст, путешествия, заметки, тревел, travel, блог]
  author: skndlst
  images: ["yclgaVppGh8.jpg"]
  DateFormat: "02-01-2006"
  defaultTheme: auto # dark, light  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false








  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: favicon.ico
    favicon16x16: favicon-16x16.png
    favicon32x32: favicon-32x32.png
    apple_touch_icon: apple-touch-icon.png
    safari_pinned_tab: apple-touch-icon.png

  label:
    text: "SKNDLST"
    icon: d-r-i.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: SKNDLST
    subtitle: "This is subtitle"
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Здарова, девки и мужики! \U0001F44B"
    Content: Всем привет! Меня зовут Миша. Здесь я публикую дневники своих путешествий, просто мысли о житухе и всякое разное, что еще взбредет в голову. Приглашаю вас почитать о том, как меня помотала жизнь.

  socialIcons:
    - name: instagram
      url: "https://www.instagram.com/mskndlst/"
    - name: telegram
      url: "https://t.me/+z8EH2y0znjE5ODhi"


  analytics:
    google:
      SiteVerificationTag: "G-VDHW86HXSN"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page



  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: сategories
      name: Категории
      url: /categories/
      weight: 10
    - identifier: tags
      name: Теги
      url: /tags/
      weight: 20
    - identifier: donut
      name: Поддержать
      url: https://www.tinkoff.ru/cf/AuFj393CCE4
      weight: 30

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai